### ISSUE TITLE
not an issue - readme clarification mmcat

### ISSUE THREAD

**Issue by johndpope** [cugu/afro#1]
I took a look at sleuth kit - 

https://github.com/sleuthkit/sleuthkit/tree/develop/win32/mmcat

it seems to only run on pc 

I'm using mac and it's possible to clone drive/partition with dd using dd
sudo dd if=/dev/disk2 of=test.dd bs=1m

am testing this out. These are the instructions - was going to update readme with link to help others - 
https://www.cyberciti.biz/faq/how-to-create-disk-image-on-mac-os-x-with-dd-command/

presumably this same as mmcat.

**Comment by cugu** [comment]
The sleuth kit is available for every major platform. 

Easiest to install on MacOS is with [brew](https://brew.sh): `brew install sleuthkit`

mmcat can extract a volume. Your dd command just creates a disk image. The volume extraction still needs to be done before using afro.

**Comment by johndpope** [comment]
thx

**Comment by cugu** [comment]
I added some clarification to the README. Thanks for asking ;-)
