### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by liwenjie0728** [cugu/afro#10]
![image](https://user-images.githubusercontent.com/15979538/47691461-180dd980-dc2d-11e8-89c7-1edd135783c9.png)
Hello,i have met this problem when using your project to recover the image.Have you met it?Can you help me，Thanks!
And why the save files size are all zero？

**Comment by cugu** [comment]
Can you provide some more information? What kind of image do you use? What command do you use to recover the files?

**Comment by liwenjie0728** [comment]
i just use the test image,and the command is the same as you suggest.but the save files size are zero

**Comment by cugu** [comment]
Okay, should be fixed now.

**Comment by cugu** [comment]
Thanks for the report 👍
