### ISSUE TITLE
how to finish searching in advance？

### ISSUE THREAD

**Issue by liwenjie0728** [cugu/afro#11]
@cugu i find you traverse every block to search the recovery files，but there are many unused blocks at the back of the volume,so how can we finish searching in advance?

**Comment by cugu** [comment]
There is always the possibility that there might be remaining data in these blocks.

**Comment by liwenjie0728** [comment]
so if we want to recover the deleted files completely，we should traverse the all blocks?

**Comment by cugu** [comment]
Yes
