### ISSUE TITLE
Update apfs.ksy

### ISSUE THREAD

**Issue by johndpope** [cugu/afro#3]
carefully looking through this file /it seems there maybe some bugs with apfs.fsk
https://github.com/ydkhatri/APFS_010/blob/master/apfs.010.bt#L455

**Comment by cugu** [comment]
Well, it needs an update from https://github.com/cugu/apfs.ksy/blob/master/apfs.ksy and some testing.

**Comment by johndpope** [comment]
I'm not a python coder - but saw this

```python
   func __init__(self, _io, _parent=None, _root=None):
        self._io = _io
        self._parent = _parent
        self._root = _root if _root else self

// should be equivalent???  unless you actually want it to be none. 
   func __init__(self, _io, _parent=None, _root=self):
        self._io = _io
        self._parent = _parent
        self._root = _root
```
